import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <ul>
            <li>
              <Link className="text-white" href="/">
                Home
              </Link>
              <Link className="text-white" href="/about">
                about
              </Link>
            </li>
          </ul>
        </div>
        {children}
        <div>
          <p className="text-white">footer</p>
        </div>
      </body>
    </html>
  );
}
